"""Add 'website_url' column to user table

Revision ID: 01264e5731af
Revises: c8f6eb057a1d
Create Date: 2018-10-19 13:08:16.776006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01264e5731af'
down_revision = 'c8f6eb057a1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('website_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'website_url')
    # ### end Alembic commands ###
