"""Add profile_picture column to user table

Revision ID: 10866fe46656
Revises: 01264e5731af
Create Date: 2018-10-21 18:01:07.354170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10866fe46656'
down_revision = '01264e5731af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_photo', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_photo')
    # ### end Alembic commands ###
