"""Add post comment likes table

Revision ID: 440ea5221252
Revises: e423b2f745a1
Create Date: 2018-10-04 15:32:38.105856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440ea5221252'
down_revision = 'e423b2f745a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_comment_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['post_comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_comment_like')
    # ### end Alembic commands ###
