"""Change about_me to bio

Revision ID: 6784fa8e7d59
Revises: a13e52dd0eaa
Create Date: 2018-09-29 08:30:18.145266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6784fa8e7d59'
down_revision = 'a13e52dd0eaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.Text(), nullable=True))
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', mysql.TEXT(), nullable=True))
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
