"""Add follow_notification table

Revision ID: 6f6f994ce4a0
Revises: 921c42b9c9c7
Create Date: 2018-10-13 11:55:49.765417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f6f994ce4a0'
down_revision = '921c42b9c9c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('notified_id', sa.Integer(), nullable=True),
    sa.Column('notifier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notified_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['notifier_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_notification_created'), 'follow_notification', ['created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_follow_notification_created'), table_name='follow_notification')
    op.drop_table('follow_notification')
    # ### end Alembic commands ###
