"""Add comment_id to post_notification table

Revision ID: 7c7e249a974b
Revises: 4b9d7ff5732b
Create Date: 2018-10-07 20:14:43.077678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7e249a974b'
down_revision = '4b9d7ff5732b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_notification', sa.Column('comment_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_notification', 'comment_id')
    # ### end Alembic commands ###
