"""Add notification table

Revision ID: 8506b6ebae9e
Revises: d80adb49a42d
Create Date: 2018-09-29 20:49:53.257358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8506b6ebae9e'
down_revision = 'd80adb49a42d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.Float(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_created'), 'notification', ['created'], unique=False)
    op.create_index(op.f('ix_notification_name'), 'notification', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_name'), table_name='notification')
    op.drop_index(op.f('ix_notification_created'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
