"""Add notification_last_read_time column to user table

Revision ID: cbf16befec5d
Revises: 440ea5221252
Create Date: 2018-10-06 14:46:03.700986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf16befec5d'
down_revision = '440ea5221252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('notification_last_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'notification_last_read_time')
    # ### end Alembic commands ###
