"""Replace PostNotification and CommentNotification tables with one Notification

Revision ID: d65752cc0dbe
Revises: f93d1bfa86af
Create Date: 2018-10-14 08:42:25.947634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd65752cc0dbe'
down_revision = 'f93d1bfa86af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comment_notification_created', table_name='comment_notification')
    op.drop_table('comment_notification')
    op.drop_index('ix_post_notification_created', table_name='post_notification')
    op.drop_table('post_notification')
    op.drop_index('ix_follow_notification_created', table_name='follow_notification')
    op.drop_table('follow_notification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_notification',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.Column('notified_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('notifier_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['notified_id'], ['user.id'], name='follow_notification_ibfk_1'),
    sa.ForeignKeyConstraint(['notifier_id'], ['user.id'], name='follow_notification_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_follow_notification_created', 'follow_notification', ['created'], unique=False)
    op.create_table('post_notification',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('notifier_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('notified_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['notified_id'], ['user.id'], name='post_notification_ibfk_1'),
    sa.ForeignKeyConstraint(['notifier_id'], ['user.id'], name='post_notification_ibfk_2'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='post_notification_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_post_notification_created', 'post_notification', ['created'], unique=False)
    op.create_table('comment_notification',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('notifier_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('notified_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['post_comment.id'], name='comment_notification_ibfk_1'),
    sa.ForeignKeyConstraint(['notified_id'], ['user.id'], name='comment_notification_ibfk_2'),
    sa.ForeignKeyConstraint(['notifier_id'], ['user.id'], name='comment_notification_ibfk_3'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='comment_notification_ibfk_4'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_comment_notification_created', 'comment_notification', ['created'], unique=False)
    # ### end Alembic commands ###
