"""Add post_notification and comment_notification tables

Revision ID: e35b82b70f75
Revises: cbf16befec5d
Create Date: 2018-10-08 09:01:39.093288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e35b82b70f75'
down_revision = 'cbf16befec5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('notifier_id', sa.Integer(), nullable=True),
    sa.Column('notified_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notified_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['notifier_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_notification_created'), 'post_notification', ['created'], unique=False)
    op.create_table('comment_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('notifier_id', sa.Integer(), nullable=True),
    sa.Column('notified_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['post_comment.id'], ),
    sa.ForeignKeyConstraint(['notified_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['notifier_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_notification_created'), 'comment_notification', ['created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_notification_created'), table_name='comment_notification')
    op.drop_table('comment_notification')
    op.drop_index(op.f('ix_post_notification_created'), table_name='post_notification')
    op.drop_table('post_notification')
    # ### end Alembic commands ###
