"""Alter notification table

Revision ID: f5f8924f6b08
Revises: d7283dda6635
Create Date: 2018-09-29 20:52:31.483411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5f8924f6b08'
down_revision = 'd7283dda6635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'created',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.create_index(op.f('ix_notification_created'), 'notification', ['created'], unique=False)
    op.drop_column('notification', 'updated')
    op.drop_column('notification', 'active')
    op.drop_column('notification', 'deleted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('deleted', mysql.DATETIME(), nullable=True))
    op.add_column('notification', sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('notification', sa.Column('updated', mysql.DATETIME(), nullable=False))
    op.drop_index(op.f('ix_notification_created'), table_name='notification')
    op.alter_column('notification', 'created',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
